name: Ingest uplink into database.json

on:
  repository_dispatch:
    types: [uplink]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout beta branch
        uses: actions/checkout@v4
        with:
          ref: beta

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Append payload into database.json
        run: |
          set -e
          FILE="database.json"
          if [ ! -f "$FILE" ]; then
            echo "[]" > "$FILE"
          fi
          # Lire le payload envoyé (client_payload)
          PAYLOAD=$(jq -c '.client_payload' "$GITHUB_EVENT_PATH")

          # Sécurité: si pas de payload → stop net
          if [ "$PAYLOAD" = "null" ] || [ -z "$PAYLOAD" ]; then
            echo "❌ Aucun client_payload reçu"; exit 1
          fi

          # Extraire un id unique (obligatoire pour éviter les doublons)
          ID=$(echo "$PAYLOAD" | jq -r '.id // empty')
          if [ -z "$ID" ]; then
            echo "❌ client_payload.id est requis (string unique)"; exit 1
          fi

          # Charger la base
          TMP="$(mktemp)"
          cat "$FILE" | jq '.' > "$TMP" || (echo "❌ $FILE invalide"; exit 1)

          # Vérifier doublon par id
          EXISTS=$(cat "$TMP" | jq --arg id "$ID" '[.[] | select(.id==$id)] | length')
          if [ "$EXISTS" != "0" ]; then
            echo "ℹ️  id=$ID déjà présent → rien à faire."
            exit 0
          fi

          # Append
          NEW=$(jq --argjson rec "$PAYLOAD" '. + [$rec]' "$TMP")
          echo "$NEW" | jq '.' > "$FILE"

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ingest: add record via repository_dispatch"
          branch: beta
          # Utilise le token GitHub Actions pour push
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          # Si tu utilises un PAT, décommente la ligne suivante et ajoute le secret dans ton repo
          # github_token: ${{ secrets.GH_PAT }}
